# Site settings
title: My Blog
description: My personal blog for sharing random musings and insights on a variety of subjects, regardless of my expertise. Join me in exploring ideas and sparking conversations.
url: https://ruifilipecampos.github.io
author:
  name: Rui Campos
  email: mail@ruicampos.org

# Build settings
theme: minima
permalink: /:title/

# Social media settings
github_username: RuiFilipeCampos


lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
