# Site settings
title: Rui's Thought Canvas
description: My personal blog for sharing random musings and insights on a variety of subjects, regardless of my expertise. Join me in exploring ideas and sparking conversations.
url: https://ruifilipecampos.github.io


# Build settings
theme: minima
permalink: /:title/

# Social media settings
github_username: RuiFilipeCampos

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
