# Site settings
title: My Blog
description: A simple blog powered by Jekyll and GitHub Pages
url: https://myusername.github.io

# Build settings
theme: jekyll-theme-cayman
permalink: /:title/

# Social media settings
twitter_username: mytwitterhandle
github_username: mygithubusername


lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
